services:
  frontend:
    build:
      context: .
      dockerfile: ./build/package/prod/frontend.prod.dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./build/package/prod/backend.prod.dockerfile
    ports:
      - "8082:8080"
    restart: unless-stopped
