services:
  frontend:
    build:
      context: .
      dockerfile: ./build/package/dev/frontend.dev.dockerfile
    volumes:
      - ./web:/app # Mount the source code directory to allow for hot-reloading
      - /app/node_modules  # Don't overwrite node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: .
      dockerfile: ./build/package/dev/backend.dev.dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development